---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info to be deleted
    os_server_info:
      cloud: openstack
    register: to_delete
    
  - name: Delete instances
    os_server:
      cloud: openstack
      state: absent
      name: "{{ item.name }}"
    loop: "{{ to_delete.openstack_servers }}"
   
